#!/bin/bash
#
# pt-kill   This shell script takes care of starting and stopping
#               the pt-kill services.
#
# chkconfig: - 60 20
# description: pt-kill stops long running MySQL queries
#
# probe: true

# Source function library.
. /lib/lsb/init-functions
#. /etc/rc.d/init.d/functions

RETVAL=0

KILLLOG="/var/log/mysql-kill.log"
KILLLOGARCHIVE="/var/log/mysql-kill-archive.log"
#EMAILS="***REMOVED*** it-monitoring@***REMOVED***.com it-team@***REMOVED***.com"
EMAILS="***REMOVED***@***REMOVED***.com"


ptk_start () {
    pt-kill \
      --pid /var/run/pt-kill.pid \
      --daemonize \
      --interval 30s
      --busy-time 600s \
      --wait-after-kill 15s \
      --ignore-info '(?i-smx:^insert|^update|^delete|^load|mailqueue)' \
      --ignore-user '(?i-xsm:***REMOVED***)' \
      --match-user '(?i-xsm:sqluser)' \
      --match-info '(?i-xsm:select)' \
      --log "$KILLLOG" \
      --execute-command '/***REMOVED***/scripts/pt-kill-exec.sh' \
      --print \
      --kill-query
}

# See how we were called.
case "$1" in
  start)
    echo -n $"Starting pt-kill: "
    ptk_start

    RETVAL=$?
    echo
    [ $RETVAL -ne 0 ] && exit $RETVAL

  ;;
  stop)
        # Stop daemons.
        echo -n $"Shutting down pt-kill: "
        #killproc pt-kill
        kill -9 $(ps aux | grep pt-kill | head -n1 | awk '{ print $2 }')
        rm -f /var/run/pt-kill.pid
        echo
    ;;
  restart)
    $0 stop
        $0 start
        ;;
  *)
        echo $"Usage: pt-kill {start|stop}"
        RETVAL=3
        ;;
esac

exit $RETVAL
